runtime: php55
api_version: 1

beta_settings:
      cloud_sql_instances: "khubaib13102:asia-south1:khubaib13102"

handlers:
- url: /(.+\.php)$
  script: \1



env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: 'mysql:unix_socket=/cloudsql/khubaib13102:asia-south1:khubaib13102;dbname=khubaib13102'
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: ''
